# Generated by Django 3.2.14 on 2022-07-28 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20220725_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='excerpt',
        ),
    ]
