# Generated by Django 3.2.14 on 2022-09-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_remove_location_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.CharField(choices=[('Connaught', 'Connaught'), ('Leinster', 'Leinster'), ('Munster', 'Munster'), ('Ulster', 'Ulster')], max_length=20),
        ),
    ]
