# Generated by Django 3.2.14 on 2022-09-07 08:32

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('locations', '0008_alter_location_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('full_name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('profile_pic', cloudinary.models.CloudinaryField(default='placeholder_profile_image', max_length=255, verbose_name='image')),
                ('slug', models.SlugField(max_length=150)),
            ],
        ),
    ]
